version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "America/New_York"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "America/New_York"
    groups:
      docker:
        patterns:
          - "*"
    ignore:
      - dependency-name: "python"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
