[tool.black]
line_length = 79
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 79
known_first_party = ["squarebot", "rubinobs.square.clients.squarebot", "tests"]
skip = ["docs/conf.py"]
