name: CI

"on":
  merge_group: {}
  pull_request: {}
  push:
    branches-ignore:
      # These should always correspond to pull requests, so ignore them for
      # the push trigger and let them be triggered by the pull_request
      # trigger, avoiding running the workflow twice.  This is a minor
      # optimization so there's no need to ensure this is comprehensive.
      - "dependabot/**"
      - "gh-readonly-queue/**"
      - "renovate/**"
      - "tickets/**"
      - "u/**"
    tags:
      - "*"

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - "3.12"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install nox
        run: |
          pip install --upgrade pip
          pip install --upgrade nox

      - name: Run nox
        run: "nox -s typing test"

  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          # Ensure the documentation gets the right version.
          fetch-depth: 0

      - name: Update package lists
        run: sudo apt-get update

      - name: Install extra packages
        run: sudo apt install -y graphviz

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install nox
        run: |
          pip install --upgrade pip
          pip install --upgrade nox

      - name: Run nox
        run: "nox -s docs"

      # Only attempt documentation uploads for long-lived branches, tagged
      # releases, and pull requests from ticket branches.  This avoids version
      # clutter in the docs and failures when a PR doesn't have access to
      # secrets.
      - name: Upload to LSST the Docs
        uses: lsst-sqre/ltd-upload@v1
        with:
          project: squarebot
          dir: "docs/_build/html"
          username: ${{ secrets.LTD_USERNAME }}
          password: ${{ secrets.LTD_PASSWORD }}
        if: >
          github.event_name != 'merge_group'
          && (github.event_name != 'pull_request'
            || startsWith(github.head_ref, 'tickets/'))

  build:

    runs-on: ubuntu-latest
    needs: [lint, test]

    # Only do Docker builds of tagged releases and pull requests from ticket
    # branches.  This will still trigger on pull requests from untrusted
    # repositories whose branch names match our tickets/* branch convention,
    # but in this case the build will fail with an error since the secret
    # won't be set.
    if: >
      startsWith(github.ref, 'refs/tags/')
      || startsWith(github.head_ref, 'tickets/')

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history for setuptools_scm

      - uses: lsst-sqre/build-and-push-to-ghcr@v1
        id: build
        with:
          image: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - run: echo Pushed ghcr.io/${{ github.repository }}/${{ steps.build.outputs.tag }}

  pypi:

    runs-on: ubuntu-latest
    needs: [lint, test, docs]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history for setuptools_scm

      - name: Build and publish
        uses: lsst-sqre/build-and-publish-to-pypi@v1
        with:
          pypi-token: ${{ secrets.PYPI_SQRE_ADMIN }}
          python-version: "3.12"
          upload: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
          working-directory: "./client"
